### ISSUE TITLE
Complex resolves of Output fields are inconsistent

### ISSUE THREAD

**Issue by tloisel1** [perfectsense/gyro#203]
**Describe the bug**
I am creating an AWS CloudWatch Alarm that needs to include the ARN of an Autoscaling Group policy. The policy ARN is an output field and isn't resolved correctly.

**To Reproduce**
Autoscale group:
```
aws::autoscaling-group frontend
    name: 'frontend-autoscale-group'
    launch-configuration: $(aws::launch-configuration frontend)
    subnets: [
        $(aws::subnet "private-us-east-1a"),
        $(aws::subnet "private-us-east-1b")
    ]
    health-check-type: "EC2"
    classic-load-balancers: [
        $(aws::load-balancer frontend)
    ]

    desired-capacity: 2
    min-size: 2
    max-size: 2

    scaling-policy
        policy-name: "Scale Up"
        adjustment-type: "ChangeInCapacity"
        policy-type: "SimpleScaling"
        cooldown: 120
        scaling-adjustment: 4
    end
end
```
CloudWatch Alarm Configuration:
```
aws::cloudwatch-metric-alarm frontend-scale-up
    name: "frontend-scale-up"
    comparison-operator: "GreaterThanThreshold"
    threshold: 60
    evaluation-periods: 1
    metric-name: "CPUUtilization"
    period: 60
    namespace: "AWS/EC2"
    statistic: "Average"
    alarm-actions: [ "\($($(aws::autoscaling-group frontend).scaling-policy | policy-name = 'Scale Up').'0'.policy-arn)" ]
end
```

**Expected behavior**
Gyro should be able to resolve dependencies to create resources in the correct order. Another caveat is that if the reference is placed in a variable, AND the scaling policy has been previously created, the reference resolves correctly:
```
frontend-scale-up-policy-arn: "\($($(aws::autoscaling-group frontend).scaling-policy | policy-name = 'Scale Up').'0'.policy-arn)"

aws::cloudwatch-metric-alarm frontend-scale-up
    name: "\($project)-frontend-scale-up"
    comparison-operator: "GreaterThanThreshold"
    threshold: 60
    evaluation-periods: 1
    metric-name: "CPUUtilization"
    period: 60
    namespace: "AWS/EC2"
    statistic: "Average"
    alarm-actions: [ $frontend-scale-up-policy-arn ]
end
```

**Stacktrace**
If applicable, cut and paste any stacktrace or error message to help explain your problem.
```
Error: Can't update aws::cloudwatch-metric-alarm frontend-scale-up resource!

Caused by: Unexpected error: software.amazon.awssdk.services.cloudwatch.model.CloudWatchException: Invalid arn syntax: <output> (Service: CloudWatch, Status Code: 400, Request ID: b8b592ae-b178-49a5-b0d3-ae406fd71a8e)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleErrorResponse(HandleResponseStage.java:115)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:58)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:113)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:86)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:62)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:57)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:240)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:96)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:120)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:73)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.cloudwatch.DefaultCloudWatchClient.putMetricAlarm(DefaultCloudWatchClient.java:1408)
	at gyro.aws.cloudwatch.MetricAlarmResource.saveMetricAlarm(MetricAlarmResource.java:536)
	at gyro.aws.cloudwatch.MetricAlarmResource.update(MetricAlarmResource.java:470)
	at gyro.core.diff.Update.execute(Update.java:91)
	at gyro.core.diff.Diff.executeChange(Diff.java:407)
	at gyro.core.diff.Diff.executeCreateKeepUpdate(Diff.java:349)
	at gyro.core.diff.Diff.execute(Diff.java:341)
	at gyro.core.command.UpCommand.doExecute(UpCommand.java:55)
	at gyro.core.command.AbstractConfigCommand.doExecute(AbstractConfigCommand.java:135)
	at gyro.core.command.AbstractCommand.execute(AbstractCommand.java:71)
	at gyro.cli.Gyro.run(Gyro.java:195)
	at gyro.cli.Gyro.main(Gyro.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by tloisel1** [comment]
Adding critical priority since autoscale triggers cannot be made without a fix.
